### ISSUE TITLE
option to not exclude anything

### ISSUE THREAD

**Issue by dmitriiabramov** [istanbuljs/test-exclude#7]
i wonder why there has to be a check for a not-empty array over here
https://github.com/istanbuljs/test-exclude/blob/master/index.js#L21
```js
  if (!this.exclude || (Array.isArray(this.exclude) && !this.exclude.length)) {
    this.exclude = [
      'test/**',
      'test{,-*}.js',
      '**/*.test.js',
      '**/__tests__/**'
    ]
  }
```

i'm trying to test the instrumentation code and obviously it gets excluded :)
All i'm trying to do is to configure the `babel-plugin-istanbul` to not exclude anything
```
babel.transform(content, {
  filename,
  plugins: [[babelPluginIstanbul, {exclude: []}]],
}).code;
```

but because of this check, the excludes get their default value.

can it be just
```js
if (!Array.isArray(this.exclude)) {
  //  this.exclude = ...
}
```

**Comment by dmitriiabramov** [comment]
this is probably related to https://github.com/istanbuljs/babel-plugin-istanbul/issues/9

**Comment by dmitriiabramov** [comment]
i can workaround by passing `excludes: [/.^/]` for now. but that's a little odd and i'd really like to just bypass the check completely :)

**Comment by bcoe** [comment]
@dmitriiabramov really open to this suggestion, if you can think of an elegant way to approach it -- ideally avoiding a breaking change.

I think it would be cool to be able to cover `node_modules`, as an example.

**Comment by dmitriiabramov** [comment]
changing it to 
```
if (!Array.isArray(this.exclude)) {
  //  this.exclude = ...
}
```

shouldn't be breaking. It'll only break if people passed an empty array an an `exclude` option in the previous versions

**Comment by JaKXz** [comment]
Want to submit a PR with tests? :)

**Comment by bcoe** [comment]
@dmitriiabramov that would be wonderful, otherwise I'm hoping Monday and Tuesday will be open source days for me.

**Comment by dmitriiabramov** [comment]
@bcoe yeah. i'll do it!
